version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - "80:80"
    volumes:
      - ./public_html:/var/www/html
      - ./virtual_hosts:/etc/apache2/sites-available
    restart: always
    networks:
      - mi-red

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - mi-red
    volumes:
      - db_data:/var/lib/mysql

networks:
  mi-red:

volumes:
  db_data:
