version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - "8080:80"
    volumes:
      - ./public_html:/var/www/html
    restart: always
    networks:
      - my-net

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      - my-net
    volumes:
      - db_data:/var/lib/mysql

networks:
  my-net:

volumes:
  db_data:
